apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-uat

commonLabels:
  environment: uat

configMapGenerator:
  - name: app-config
    literals:
      - APP_ENV=uat
      - LOG_LEVEL=warn
      - FEATURE_FLAGS=prod_like
