apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-qa

commonLabels:
  environment: qa

configMapGenerator:
  - name: app-config
    literals:
      - APP_ENV=qa
      - LOG_LEVEL=info
      - FEATURE_FLAGS=stable
